const ROME_LABELS: Record<string, string> = {
  /* Domain A — Agriculture, Marine, Pêche */
  A1101: "Conduite d'engins agricoles et forestiers",
  A1201: "Bûcheronnage et élagage",
  A1301: "Conseil et assistance technique en agriculture",
  A1401: "Aide agricole de production fruitière ou viticole",
  A1402: "Aide agricole de production légumière ou végétale",
  A1411: "Élevage bovin ou équin",
  A1413: "Élevage porcin",
  A1415: "Élevage de lapins et volailles",
  A1416: "Polyculture, élevage",

  /* Domain B — Arts et façonnage d'ouvrages d'art */
  B1101: "Création en arts plastiques",
  B1201: "Réalisation de pièces de joaillerie",
  B1301: "Décoration d'espaces de vente et d'exposition",

  /* Domain C — Banque, Assurance, Immobilier */
  C1101: "Actuariat",
  C1102: "Analyse et ingénierie financière",
  C1103: "Analyse de crédits et de risques financiers",
  C1104: "Gestion de portefeuilles sur les marchés financiers",
  C1106: "Trésorerie et financement",
  C1107: "Contrôle de gestion et audit financier",
  C1108: "Études actuarielles en assurances",
  C1201: "Accueil et services bancaires",
  C1202: "Conseil clientèle en assurances",
  C1203: "Relation clients banque/finance",
  C1204: "Conception et expertise produits bancaires et financiers",
  C1205: "Conseil en gestion de patrimoine financier",
  C1206: "Gestion de clientèle bancaire",
  C1301: "Front office marchés financiers",
  C1401: "Gestion en banque et assurance",
  C1501: "Liquidation de contrats d'assurances",
  C1502: "Souscription de contrats d'assurances",
  C1503: "Expertise risques en assurances",
  C1504: "Rédaction et gestion en assurances",
  C1510: "Gestion sinistres du secteur de l'assurance",

  /* Domain D — Commerce, Vente et Grande Distribution */
  D1101: "Boucherie",
  D1102: "Boulangerie - Viennoiserie",
  D1103: "Charcuterie - Traiteur",
  D1104: "Pâtisserie, confiserie, chocolaterie et glacerie",
  D1106: "Vente en alimentation",
  D1201: "Achat vente articles d'occasion",
  D1202: "Coiffure",
  D1203: "Hydrothérapie",
  D1204: "Manucure - Esthétique",
  D1205: "Opticien lunetier",
  D1206: "Prothèse dentaire",
  D1207: "Retouche en habillement",
  D1208: "Soins esthétiques et corporels",
  D1209: "Esthétique et cosmétique",
  D1401: "Assistanat commercial",
  D1402: "Relation commerciale grands comptes et entreprises",
  D1403: "Relation commerciale auprès de particuliers",
  D1404: "Relation commerciale en vente de véhicules",
  D1405: "Montage et financement de produits de défiscalisation",
  D1406: "Management en force de vente",
  D1407: "Relation technico-commerciale",
  D1408: "Téléconseil et télévente",
  D1501: "Animation de vente",
  D1502: "Conseil client en parfumerie et en cosmétique",
  D1503: "Défense et conseil juridique en droit du travail",
  D1504: "Marchandisage",
  D1505: "Personnel de caisse",
  D1506: "Gestion de magasin",
  D1507: "Mise en rayon libre-service",
  D1508: "Encadrement du commerce",
  D1509: "Management de département en grande distribution",

  /* Domain E — Communication, Médias et Multimédia */
  E1101: "Animation de site multimédia",
  E1102: "Écriture d'ouvrages, de livres",
  E1103: "Communication",
  E1104: "Conception de contenus multimédias",
  E1105: "Coordination d'édition",
  E1106: "Journalisme et information média",
  E1107: "Organisation d'évènements culturels et festifs",
  E1108: "Traduction, interprétation",
  E1201: "Photographie",
  E1301: "Décoration intérieure et merchandising",
  E1302: "Production en laboratoire cinématographique",
  E1303: "Production et administration spectacle, cinéma et audiovisuel",
  E1304: "Réalisation cinématographique et audiovisuelle",
  E1305: "Tournage et traitement de l'image et du son",
  E1306: "Coordination de production cinéma et audiovisuel",
  E1307: "Montage audiovisuel et multimédia",
  E1401: "Développement et promotion publicitaire",

  /* Domain F — Construction, Bâtiment et Travaux Publics */
  F1101: "Architecture du BTP et du paysage",
  F1102: "Conception - aménagement d'espaces intérieurs",
  F1103: "Contrôle et diagnostic technique du bâtiment",
  F1104: "Dessin BTP et infrastructures",
  F1105: "Études géotechniques",
  F1106: "Ingénierie et études du BTP",
  F1201: "Conduite de chantier du BTP",
  F1202: "Direction de chantier du BTP",
  F1203: "Direction et ingénierie d'exploitation de gisements et de carrières",
  F1301: "Conduite de travaux du BTP et de travaux paysagers",
  F1302: "Direction de projet BTP",
  F1401: "Extraction liquides et gaz",
  F1402: "Extraction solide",
  F1501: "Montage de structures et de charpentes",
  F1502: "Montage-installation d'équipements électriques et électroniques",
  F1503: "Installation du réseau électrique et de télécommunication",
  F1601: "Application et décoration en plâtre, stuc et staff",
  F1602: "Électricité bâtiment",
  F1603: "Installation d'équipements sanitaires et thermiques",
  F1604: "Montage d'agencements",
  F1605: "Montage de mobilier",
  F1606: "Peinture en bâtiment",
  F1607: "Pose de fermetures menuisées",
  F1608: "Pose de revêtements rigides",
  F1609: "Pose de revêtements souples",
  F1610: "Pose et restauration de couvertures",
  F1611: "Réalisation et restauration de façades",
  F1612: "Taille de pierres",
  F1701: "Construction en béton",
  F1702: "Construction de routes et voies",
  F1703: "Maçonnerie",

  /* Domain G — Hôtellerie-Restauration, Tourisme, Loisirs */
  G1101: "Accueil touristique",
  G1102: "Promotion du tourisme local",
  G1201: "Accompagnement de voyages, d'activités culturelles ou sportives",
  G1202: "Animation d'activités culturelles ou ludiques",
  G1203: "Animation de loisirs sportifs",
  G1204: "Éducation en activités sportives",
  G1205: "Personnel d'attractions ou de structures de loisirs",
  G1206: "Personnel navigant de cabine",
  G1301: "Conception de produits touristiques",
  G1401: "Assistance de direction d'hôtel-restaurant",
  G1402: "Management d'hôtel-restaurant",
  G1403: "Gestion de structure de loisirs ou d'hébergement touristique",
  G1404: "Management de site touristique",
  G1501: "Personnel d'étage en hôtellerie",
  G1502: "Personnel polyvalent d'hôtellerie",
  G1601: "Management du personnel de cuisine",
  G1602: "Personnel de cuisine",
  G1603: "Personnel polyvalent en restauration",
  G1604: "Fabrication de crêpes ou pizzas",
  G1605: "Plonge en restauration",
  G1701: "Café, bar brasserie",
  G1702: "Personnel de salle restauration",
  G1703: "Service en restauration",
  G1801: "Encadrement de la plaisance",
  G1802: "Pêche professionnelle en mer, en eau douce",

  /* Domain H — Industrie */
  H1101: "Assistance et support technique client",
  H1102: "Management et ingénierie d'affaires industrielles",
  H1201: "Expertise technique couleur en industrie",
  H1202: "Réalisation de prototypes",
  H1203: "Conception et dessin de produits électriques et électroniques",
  H1204: "Design industriel",
  H1205: "Études et conception en automatisme",
  H1206: "Management et ingénierie études, recherche et développement industriel",
  H1207: "Rédaction technique",
  H1208: "Intervention technique en études et conception en automatisme",
  H1209: "Intervention technique en études, recherche et développement",
  H1210: "Intervention technique en dessin industriel",
  H1301: "Inspection de conformité",
  H1302: "Management et ingénierie hygiène sécurité environnement",
  H1303: "Intervention technique en hygiène, sécurité et environnement industriels",
  H1401: "Management et ingénierie gestion industrielle et logistique",
  H1402: "Management et ingénierie méthodes et industrialisation",
  H1403: "Intervention technique en gestion industrielle et logistique",
  H1404: "Intervention technique en méthodes et industrialisation",
  H1501: "Direction de laboratoire d'analyse industrielle",
  H1502: "Management et ingénierie de production",
  H1503: "Pilotage d'installation automatisée ou robotisée",
  H1504: "Encadrement d'équipe en industrie de transformation",
  H2101: "Abattage et découpe des viandes",
  H2102: "Fabrication de produits carnés",
  H2201: "Boissons alcoolisées - Vins et spiritueux",
  H2202: "Boissons sans alcool et produits frais",
  H2203: "Industrie des corps gras",
  H2204: "Industrie du sucre et des confiseries",
  H2301: "Assemblage d'ouvrages en bois",
  H2302: "Encadrement des industries du bois et de l'ameublement",
  H2401: "Assemblage - montage de matériels",
  H2402: "Assemblage assemblage et montage de véhicules",
  H2503: "Montage de systèmes hydrauliques et pneumatiques",
  H3302: "Réglage d'équipements de production industrielle",
  H3303: "Encadrement d'équipe ou d'atelier en usinage-taille de matériaux",

  /* Domain I — Installation et Maintenance */
  I1101: "Direction et ingénierie en entretien infrastructure et bâti",
  I1102: "Management et ingénierie de maintenance industrielle",
  I1103: "Supervision d'entretien et gestion de patrimoine immobilier",
  I1201: "Entretien de locaux",
  I1202: "Lavage de vitres",
  I1203: "Maintenance des bâtiments et des locaux",
  I1301: "Installation et maintenance d'ascenseurs",
  I1302: "Installation et maintenance d'automatismes",
  I1303: "Installation et maintenance de distributeurs automatiques",
  I1304: "Installation et maintenance en froid, conditionnement d'air",
  I1305: "Installation et maintenance électronique",
  I1306: "Installation et maintenance en génie thermique et énergie",
  I1307: "Installation et maintenance télécoms et courants faibles",
  I1401: "Maintenance informatique et bureautique",
  I1402: "Réparation de biens électrodomestiques",
  I1403: "Réparation de biens électroniques et électroménagers",
  I1404: "Réparation - montage articles chaussures et maroquinerie",
  I1501: "Entretien d'aéronefs",
  I1502: "Entretien de matériels d'exploitation agricole",
  I1503: "Entretien de trains et transports guidés",
  I1504: "Mécanique automobile et entretien de véhicules",
  I1505: "Entretien d'engins de chantier, levage, manutention et de machines agricoles",
  I1601: "Installation et maintenance en nautisme",
  I1607: "Maintenance d'installations de parcs et attractions",

  /* Domain J — Santé */
  J1101: "Médecine de médecine générale",
  J1102: "Médecine spécialisée",
  J1103: "Médecine dentaire",
  J1104: "Suivi de la grossesse et de l'accouchement",
  J1105: "Médecine nucléaire",
  J1201: "Biologie médicale",
  J1202: "Pharmacie",
  J1301: "Nursing",
  J1302: "Analyses médicales",
  J1303: "Assistance médicale",
  J1304: "Aide en puériculture",
  J1305: "Conduite de véhicules sanitaires",
  J1306: "Imagerie médicale",
  J1307: "Préparation en pharmacie",
  J1401: "Ergothérapie",
  J1402: "Kinésithérapie",
  J1403: "Optométrie - orthoptie",
  J1404: "Orthophonie",
  J1405: "Pédicurie podologie",
  J1406: "Rééducation en psychomotricité",
  J1501: "Diététique",
  J1502: "Ergonomie",
  J1503: "Hygiène en milieu hospitalier",
  J1504: "Information médicale",
  J1505: "Psychologie",

  /* Domain K — Services à la Personne et à la Collectivité */
  K1101: "Accompagnement et aide aux personnes en situation de handicap",
  K1102: "Aide aux bénéficiaires de minima sociaux",
  K1103: "Développement personnel et bien-être de la personne",
  K1104: "Psychologie",
  K1201: "Action sociale",
  K1202: "Éducation de jeunes enfants",
  K1203: "Encadrement technique en insertion professionnelle",
  K1204: "Médiation sociale et facilitation de la vie en société",
  K1205: "Information sociale",
  K1206: "Intervention socioéducative",
  K1207: "Intervention socioculturelle",
  K1401: "Conception et pilotage de la politique des pouvoirs publics",
  K1402: "Conseil général des ministères",
  K1403: "Management de structure de santé, sociale ou pénitentiaire",
  K1404: "Mise en œuvre et pilotage de la politique des pouvoirs publics",
  K1405: "Représentation de l'État sur le territoire national ou international",
  K1501: "Application des règles financières publiques",
  K1502: "Contrôle et inspection des Affaires Sociales",
  K1503: "Contrôle et inspection fiscale",
  K1504: "Contrôle et inspection d'un espace naturel et marin",
  K1601: "Cybersécurité",
  K1602: "Défense nationale",
  K1604: "Contrôle et police des frontières",
  K1701: "Intervention en situation d'urgence",
  K1702: "Surveillance municipale",
  K1703: "Sécurité et surveillance privées",
  K2101: "Aide à domicile",
  K2102: "Garde d'enfants à domicile",
  K2104: "Nettoyage de locaux",
  K2111: "Services domestiques",

  /* Domain L — Spectacle */
  L1101: "Adaptation et transposition artistiques",
  L1201: "Danse",
  L1202: "Musique et chant",
  L1203: "Art dramatique",
  L1301: "Mise en scène de spectacles vivants",
  L1302: "Production cinématographique, audiovisuelle",
  L1401: "Réalisation de contenus numériques",
  L1501: "Séquences et chorégraphies",
  L1510: "Animation culturelle et ludique",

  /* Domain M — Support à l'Entreprise (IT & gestion) */
  M1101: "Achats",
  M1102: "Direction des achats",
  M1201: "Analyse et ingénierie financière",
  M1202: "Audit et contrôle comptables et financiers",
  M1203: "Comptabilité",
  M1204: "Contrôle de gestion",
  M1205: "Direction administrative et financière",
  M1206: "Management de groupe ou de service comptable",
  M1207: "Trésorerie et financement d'entreprise",
  M1301: "Direction de grande entreprise ou d'établissement public",
  M1302: "Direction de petite ou moyenne entreprise",
  M1401: "Conduite d'enquêtes",
  M1402: "Conseil en organisation et management d'entreprise",
  M1403: "Études et prospectives socio-économiques",
  M1501: "Assistanat en ressources humaines",
  M1502: "Développement des ressources humaines",
  M1503: "Management des ressources humaines",
  M1601: "Accueil et renseignements",
  M1602: "Opérations administratives",
  M1603: "Distribution de documents",
  M1604: "Assistanat de direction",
  M1605: "Assistanat technique et administratif",
  M1606: "Saisie de données",
  M1607: "Secrétariat",
  M1608: "Gestion des opérations administratives",

  /* Domain M18 — Systèmes d'information / Informatique */
  M1801: "Administration de systèmes d'information",
  M1802: "Expertise et support en systèmes d'information",
  M1803: "Direction des systèmes d'information",
  M1804: "Études et développement de réseaux de télécoms",
  M1805: "Études et développement informatique",
  M1806: "Conseil et maîtrise d'ouvrage en systèmes d'information",
  M1807: "Exploitation de systèmes de communication et de commandement",
  M1808: "Télémaintenance",
  M1809: "Exploitation de systèmes informatiques",

  /* Domain N — Transport et Logistique */
  N1101: "Conduite d'engins de déplacement des charges",
  N1102: "Déménagement",
  N1103: "Magasinage et préparation de commandes",
  N1104: "Manœuvre et conduite d'engins lourds de manutention",
  N1105: "Réception et expédition de marchandises",
  N1201: "Affrètement transport",
  N1202: "Gestion des opérations de transport international de marchandises",
  N1301: "Conception et organisation de la chaîne logistique",
  N1302: "Direction de site logistique",
  N1303: "Intervention technique d'exploitation logistique",
  N2101: "Navigation commerciale aérienne",
  N2102: "Pilotage et navigation technique aérienne",
  N2201: "Navigation fluviale",
  N2202: "Navigation maritime",
  N3101: "Encadrement du transport de personnes",
  N3102: "Supervision d'exploitation éco-industrielle",
  N3103: "Transport de particuliers",
  N3104: "Transports en commun",
  N3105: "Conduite et livraison par tournée sur courte distance",
  N4101: "Conduite de transport en commun sur route",
  N4102: "Conduite de véhicules légers",
  N4103: "Conduite de transport de marchandises sur longue distance",
  N4104: "Courses et livraisons express",
  N4105: "Déménagement",
  N4201: "Entretien des espaces verts",
  N4402: "Conduite de train et métro",
  N4403: "Aiguillage et sécurité ferroviaire",
};

export function getRomeLabel(code: string): string {
  return ROME_LABELS[code.toUpperCase()] ?? code;
}
