import booleanPointInPolygon from "@turf/boolean-point-in-polygon";
import type { Feature, FeatureCollection, MultiPolygon, Polygon, Position } from "geojson";

/** Bounding box as [west, south, east, north]. */
export type Bbox = [number, number, number, number];

export type CommuneGeometry = Feature<
  Polygon | MultiPolygon,
  { code: string; nom: string; pop: number }
>;

export interface CommuneFeature {
  code: string;
  nom: string;
  /** Population (0 when unknown) — drives the zoom level at which the name label appears. */
  pop: number;
  dept: string;
  bbox: Bbox;
  feature: CommuneGeometry;
}

const GEO_BASE = "/geo/communes";
const GEO_HD_BASE = "/geo/communes-hd";

/** Load the department contours used as the stylised basemap. */
export async function loadDepartementContours(): Promise<
  FeatureCollection<Polygon | MultiPolygon, { code: string; nom: string }>
> {
  const res = await fetch("/geo/departements.geojson");
  if (!res.ok) throw new Error(`Failed to load departement contours (HTTP ${res.status})`);
  return res.json() as Promise<
    FeatureCollection<Polygon | MultiPolygon, { code: string; nom: string }>
  >;
}

/** Load the department code → bbox index generated by scripts/build-communes-geo.mjs. */
export async function loadDeptIndex(): Promise<Record<string, Bbox>> {
  const res = await fetch(`${GEO_BASE}/index.json`);
  if (!res.ok) throw new Error(`Failed to load commune index (HTTP ${res.status})`);
  return res.json() as Promise<Record<string, Bbox>>;
}

/**
 * Load one department's commune contours and precompute per-feature bboxes.
 * `hd` picks the 100m-simplified variant (metropolitan departments only)
 * used for detailed rendering at high zoom; the default 1000m variant is
 * light enough to load for the whole country up front.
 */
export async function loadDeptCommunes(dept: string, hd = false): Promise<CommuneFeature[]> {
  const res = await fetch(`${hd ? GEO_HD_BASE : GEO_BASE}/${dept}.geojson`);
  if (!res.ok) throw new Error(`Failed to load communes for dept ${dept} (HTTP ${res.status})`);
  const collection = (await res.json()) as { features: CommuneGeometry[] };
  return collection.features.map((feature) => ({
    code: feature.properties.code,
    nom: feature.properties.nom,
    pop: feature.properties.pop ?? 0,
    dept,
    bbox: computeBbox(feature.geometry.coordinates),
    feature,
  }));
}

export function bboxContains(bbox: Bbox, lng: number, lat: number): boolean {
  return lng >= bbox[0] && lat >= bbox[1] && lng <= bbox[2] && lat <= bbox[3];
}

export function bboxIntersects(a: Bbox, b: Bbox): boolean {
  return a[0] <= b[2] && a[2] >= b[0] && a[1] <= b[3] && a[3] >= b[1];
}

const METERS_PER_DEGREE_LAT = 111_320;

/**
 * True when the commune polygon intersects a circular brush.
 *
 * The exact test is approximated by: circle center inside the polygon, or any
 * polygon vertex within the radius. With 1000m-simplified contours (vertices
 * every ~1 km) and brush radii of several km this misses nothing in practice,
 * and stays cheap enough to run on every mousemove.
 */
export function communeIntersectsCircle(
  commune: CommuneFeature,
  lng: number,
  lat: number,
  radiusMeters: number,
): boolean {
  const cosLat = Math.cos((lat * Math.PI) / 180);
  const latMargin = radiusMeters / METERS_PER_DEGREE_LAT;
  const lngMargin = radiusMeters / (METERS_PER_DEGREE_LAT * Math.max(cosLat, 0.01));
  const [w, s, e, n] = commune.bbox;
  if (lng < w - lngMargin || lat < s - latMargin || lng > e + lngMargin || lat > n + latMargin) {
    return false;
  }
  if (booleanPointInPolygon([lng, lat], commune.feature)) return true;
  return anyVertexWithin(
    commune.feature.geometry.coordinates,
    lng,
    lat,
    radiusMeters * radiusMeters,
    cosLat,
  );
}

/* Equirectangular distance — accurate enough at brush scale, no trig per vertex. */
function anyVertexWithin(
  coords: Coords,
  lng: number,
  lat: number,
  radiusSqMeters: number,
  cosLat: number,
): boolean {
  if (typeof coords[0] === "number") {
    const [vLng, vLat] = coords as Position;
    const dx = (vLng - lng) * cosLat * METERS_PER_DEGREE_LAT;
    const dy = (vLat - lat) * METERS_PER_DEGREE_LAT;
    return dx * dx + dy * dy <= radiusSqMeters;
  }
  for (const c of coords as Coords[]) {
    if (anyVertexWithin(c, lng, lat, radiusSqMeters, cosLat)) return true;
  }
  return false;
}

type Coords = Position | Coords[];

function computeBbox(coords: Coords): Bbox {
  const bbox: Bbox = [Infinity, Infinity, -Infinity, -Infinity];
  extend(bbox, coords);
  return bbox;
}

function extend(bbox: Bbox, coords: Coords): void {
  if (typeof coords[0] === "number") {
    const [lng, lat] = coords as Position;
    bbox[0] = Math.min(bbox[0], lng);
    bbox[1] = Math.min(bbox[1], lat);
    bbox[2] = Math.max(bbox[2], lng);
    bbox[3] = Math.max(bbox[3], lat);
    return;
  }
  for (const c of coords as Coords[]) extend(bbox, c);
}
