import type { Feature, MultiPolygon, Polygon, Position } from "geojson";

/** Bounding box as [west, south, east, north]. */
export type Bbox = [number, number, number, number];

export type CommuneGeometry = Feature<Polygon | MultiPolygon, { code: string; nom: string }>;

export interface CommuneFeature {
  code: string;
  nom: string;
  bbox: Bbox;
  feature: CommuneGeometry;
}

const GEO_BASE = "/geo/communes";

/** Load the department code → bbox index generated by scripts/build-communes-geo.mjs. */
export async function loadDeptIndex(): Promise<Record<string, Bbox>> {
  const res = await fetch(`${GEO_BASE}/index.json`);
  if (!res.ok) throw new Error(`Failed to load commune index (HTTP ${res.status})`);
  return res.json() as Promise<Record<string, Bbox>>;
}

/** Load one department's commune contours and precompute per-feature bboxes. */
export async function loadDeptCommunes(dept: string): Promise<CommuneFeature[]> {
  const res = await fetch(`${GEO_BASE}/${dept}.geojson`);
  if (!res.ok) throw new Error(`Failed to load communes for dept ${dept} (HTTP ${res.status})`);
  const collection = (await res.json()) as { features: CommuneGeometry[] };
  return collection.features.map((feature) => ({
    code: feature.properties.code,
    nom: feature.properties.nom,
    bbox: computeBbox(feature.geometry.coordinates),
    feature,
  }));
}

export function bboxContains(bbox: Bbox, lng: number, lat: number): boolean {
  return lng >= bbox[0] && lat >= bbox[1] && lng <= bbox[2] && lat <= bbox[3];
}

export function bboxIntersects(a: Bbox, b: Bbox): boolean {
  return a[0] <= b[2] && a[2] >= b[0] && a[1] <= b[3] && a[3] >= b[1];
}

type Coords = Position | Coords[];

function computeBbox(coords: Coords): Bbox {
  const bbox: Bbox = [Infinity, Infinity, -Infinity, -Infinity];
  extend(bbox, coords);
  return bbox;
}

function extend(bbox: Bbox, coords: Coords): void {
  if (typeof coords[0] === "number") {
    const [lng, lat] = coords as Position;
    bbox[0] = Math.min(bbox[0], lng);
    bbox[1] = Math.min(bbox[1], lat);
    bbox[2] = Math.max(bbox[2], lng);
    bbox[3] = Math.max(bbox[3], lat);
    return;
  }
  for (const c of coords as Coords[]) extend(bbox, c);
}
